### PR TITLE
CHANGELOG update for 2.4.0 release

### PR DESCRIPTION
**Pull request by miketheman**
This is in prep for a hopeful release of 2.4.0 - there's a few bugfixes that should definitely make it out.

The style adopts the [Vandamme](http://tech-angels.github.io/vandamme/) approach - something I've used in a couple of other places and it's worked out nicely.

The credits to contributors and styling is courtesy of [pimpmychangelog](https://github.com/pcreux/pimpmychangelog) - another cool mechanism to link things together for posterity.

Tagging @portertech & @coderanger

### CODE REVIEW

**Comment by coderanger** [comment]
:+1: but I don't have permissions to make releases (no upload perms on RubyGems) so I think it best to leave this to @portertech to merge.

**Comment by miketheman** [comment]
@portertech This is a docs-only change, in hopes to prepare for a release.

**Comment by miketheman** [comment]
Updated today to include most recent changeset.

It's all ready to be merged and shipped - is everything ok with @portertech ?

**Comment by miketheman** [comment]
Partially superseded by 8a8e40a8883ab1b30a40d30ef697402a92047494 - closing this one due to conflict.

Godspeed, @coderanger .

**Pull request closed without merging**
