### PR TITLE
Handle case of root user for ssh key generation

### PR DESCRIPTION
**Pull request by ytsarev**

### CODE REVIEW

**Comment by coderanger** [comment]
Hmm, a good addition but leaving the leading `/` as hardwired is odd. I would also probably add a config value for it as a manual override, but that could be another pass. Can you move the leading `/` into the two literals?

**Comment by ytsarev** [comment]
Hi, I've amended PR, thanks !

**Comment by ytsarev** [comment]
@coderanger so what about to merge ?

**Comment by coderanger** [comment]
Thanks for the patch!

**Pull request merged**
