### PR TITLE
Add support for Alpine linux platform

### PR DESCRIPTION
**Pull request by timani**
I wanted to add support for Alpine Linux as it's quite a useful distro with a small footprint around 5MB. This way it will be available as a platform when defining a `platform` in the `.kitchen.yml`

At the moment this fails as Alpine is not a supported platform:

```
# kitchen create sculpin-alpine 
-----> Starting Kitchen (v1.5.0.rc.1)
-----> Creating <sculpin-alpine>...
>>>>>> Create failed on instance <sculpin-alpine>.
>>>>>> Please see .kitchen/logs/sculpin-alpine.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Unknown platform 'alpine'
>>>>>> ----------------------
```

This PR is for:
- apk --update
- apk add openssh curl 

*Output within Container*:
https://gist.github.com/timani/03cd67a9a287c0337bdc

Are there some additional tests that would need to be run to make sure it meets the requirements? If so I can gladly add those. 

*Links*
- http://www.alpinelinux.org/
- https://hub.docker.com/_/alpine/

### CODE REVIEW

**Comment by thedrow** [comment]
Yes please. I really need this.
I'll install you're fork and see what happens.

**Comment by thedrow** [comment]
Here's a failure for you to fix:
```
STDOUT: Sending build context to Docker daemon 3.072 kB
Step 1 : FROM drifter-api/base:latest
 ---> f9b822311c35
Step 2 : RUN apk update
 ---> Running in 419d65e2ed97
fetch http://nl.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-2.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-3.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-5.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
v3.3.1-54-g542892a [http://nl.alpinelinux.org/alpine/v3.3/main]
v3.3.1-54-g542892a [http://dl-2.alpinelinux.org/alpine/v3.3/main]
v3.3.1-54-g542892a [http://dl-3.alpinelinux.org/alpine/v3.3/main]
v3.3.1-54-g542892a [http://dl-4.alpinelinux.org/alpine/v3.3/main]
v3.3.1-54-g542892a [http://dl-5.alpinelinux.org/alpine/v3.3/main]
OK: 5318 distinct packages available
 ---> 2b61f4d029f3
Removing intermediate container 419d65e2ed97
Step 3 : RUN apk add openssh curl
 ---> Running in 0b49f88bf472
(1/7) Installing openssl (1.0.2f-r0)
(2/7) Installing ca-certificates (20160104-r2)
(3/7) Installing libssh2 (1.6.0-r0)
(4/7) Installing curl (7.47.0-r0)
(5/7) Installing openssh-client (7.1_p2-r0)
(6/7) Installing openssh-sftp-server (7.1_p2-r0)
(7/7) Installing openssh (7.1_p2-r0)
Executing busybox-1.24.1-r7.trigger
Executing ca-certificates-20160104-r2.trigger
OK: 10 MiB in 18 packages
 ---> db1a4471bdf6
Removing intermediate container 0b49f88bf472
Step 4 : RUN ssh-keygen -A -t rsa -f /etc/ssh/ssh_host_rsa_key
 ---> Running in 4136b63e09aa
ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519
 ---> c07e79742aff
Removing intermediate container 4136b63e09aa
Step 5 : RUN ssh-keygen -A -t dsa -f /etc/ssh/ssh_host_dsa_key
 ---> Running in 833e94e952a0
 ---> 0a81683c5f64
Removing intermediate container 833e94e952a0
Step 6 : RUN if ! getent passwd kitchen; then                 useradd -d /home/kitchen -m -s /bin/bash kitchen;               fi
 ---> Running in a6a8e7a5834d
/bin/sh: useradd: not found

STDERR: The command '/bin/sh -c if ! getent passwd kitchen; then                 useradd -d /home/kitchen -m -s /bin/bash kitchen;               fi' returned a non-zero code: 127
---- End output of docker -H tcp://192.168.99.100:2376 build -f /Users/omer.katz/Documents/drifter/drifter-api/distribution/dependencies/Dockerfile-kitchen20160210-84186-gz7fs9 - ----
Ran docker -H tcp://192.168.99.100:2376 build -f /Users/omer.katz/Documents/drifter/drifter-api/distribution/dependencies/Dockerfile-kitchen20160210-84186-gz7fs9 - returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
The command to add a user in alpine is adduser. not useradd.

**Comment by thedrow** [comment]
You can find the code here that executes the addition of the user: https://github.com/portertech/kitchen-docker/blob/014b9aa24623d375a3a0c0595585f0d7519c8909/lib/kitchen/driver/docker.rb#L226

**Comment by thedrow** [comment]
Right now I'm stuck with:
```
[SSH] Established
       Finished creating <default-drifter-base> (0m24.11s).
-----> Converging <default-drifter-base>...
$$$$$$ Running legacy converge for 'Docker' Driver
       Preparing files for transfer
       Preparing dna.json
       Berksfile, Cheffile, cookbooks/, or metadata.rb not found so Chef will run with effectively no cookbooks. Is this intended?
       Removing non-cookbook files before transfer
       Preparing solo.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://www.chef.io/chef/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       Unable to determine platform version!
       Version:

       Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
       Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
       More Chef support resources can be found at https://www.chef.io/support

       Please include as many details about the problem as possible i.e., how to reproduce
       the problem (if possible), type of the Operating System and its version, etc.,
       and any other relevant details that might help us with troubleshooting.
```
See https://github.com/thedrow/kitchen-docker/tree/apl

**Comment by thedrow** [comment]
It does work with the dummy provider though.

**Comment by thedrow** [comment]
@timani Should I just open a new pull request?

**Comment by coderanger** [comment]
Chef does not support Alpine at this time so I'm not sure what would pass for "official support" in kitchen-docker. I think for the moment the best approach would be to use the `dockerfile` configuration option to fully specify your own config. Even with that, I don't know how you would effectively install Chef though.

**Comment by thedrow** [comment]
People use Test Kitchen for other provisioners as well.
I'd like to be able to run the tests without chef.

**Comment by peterabbott** [comment]
Even with the other provisioners Test Kitchen has a dependency on Chef as it uses some of the features bundled with it during the verify phase. It is a Test Kitchen thing not something the docker driver is doing.

Does your setup work without using Chef for thr converge? You might have to install Chef manually (if possible) as part of the setup phase using the custom provision config

**Comment by thedrow** [comment]
I'm going to use the shell verifier with serverspec on ssh mode.
I still think there's no value to reject this feature request.
More and more people will want smaller containers and Alpine can provide that.

**Comment by coderanger** [comment]
That's fair, but if you aren't using Chef you'll probably want a fairly different setup than the standard dockerfile too, maybe? A broader description of what you are trying to do with TK+Alpine would help.

**Comment by thedrow** [comment]
I'm trying to test docker images I built from the alpine base image. That's about it.

**Comment by coderanger** [comment]
Hmm, what kind of tests are you planning to run? I wouldn't normally assume that you would install sshd in an Alpine image.

**Comment by thedrow** [comment]
To check if packages are installed. Verify that they do what they declare they do etc.

**Comment by coderanger** [comment]
@thedrow If you can get this to a working state with a non-Chef provisioner, let me know. I would be cool with merging this explicitly for non-Chef use if there was an explicit check for one of the known chef-related provisioners (either by name or preferably by `is_a?(ChefBase)`) so there is a better UX than an omnibus installer error.

**Comment by thedrow** [comment]
My branch works with the none chef provider but see #194.
The shell verifier cannot work if that issue will not be resolved.

**Comment by IronCore864** [comment]
I think kitchen only uses chef because it uses the ruby and gem bundled within chef, to install busser which is the default verifier for kitchen.

While chef does not support alpine, if people do not use chef as provisioner, but something else, like kitchen-ansible, I think alpine would make sense. You can choose not to install chef but only ruby and gem.

**Comment by IronCore864** [comment]
I think kitchen only uses chef because it uses the ruby and gem bundled within chef, to install busser which is the default verifier for kitchen.

If you don't use chef provisioner, and busser is not required (or preinstalled in the docker, or just have ruby and gem in the docker and still can install busser), alpine works and it is a small and fast way to do local test.

For example, kitchen, kitchen-docker as driver, kitchen-ansible as provisioner, and alpine as container. Image size could be under 200MB even with sshd, busybox, git, ansible preinstalled.

I have already tested this locally, but with `dockerfile` option, to bypass the version check. I hope in the following days/weeks I can contribute a PR on this issue to add support for alpine and mention in the doc that you can only use this when you don't use chef as provisioner.

Weird that only me and @thedrow had this issue or requirement, although I think it makes a great sense for faster CI.

**Comment by ultrafez** [comment]
@IronCore864 You're not the only two who would find Alpine platform support useful, I'd also benefit from it. Some of our apps which we dev/test using Test Kitchen have Alpine-based Docker images as dependencies, and it would be nice to be able to use them directly as a platform without having to write a Dockerfile to support them.

**Comment by IronCore864** [comment]
@ultrafez I got a PR regarding supporting alpine:

https://github.com/test-kitchen/kitchen-docker/pull/288

It's not reviewed nor merged, because CI is failing, but according to the log, I think master branch is failing too. If you want to have something that works now you can check it out.

**Pull request closed without merging**
