### PR TITLE
Add centos 5 /etc/sudoers.d support

### PR DESCRIPTION
**Pull request by jmauntel**
Added logic to create /etc/sudoers.d directory, if missing

### CODE REVIEW

**Comment by CpuID** [comment]
+1 this is required to use kitchen-docker with centos 5

**Comment by CpuID** [comment]
@portertech bump :)

**Comment by fehwalker** [comment]
This fixes issue #99 - bump bump :)

**Comment by portertech** [comment]
Good old CentOS 5, my condolences. 

290d83c4-386d-11e4-9c09-d8370605c43d

**Pull request merged**
