### PR TITLE
Post merge adjustments, release prep

### PR DESCRIPTION
**Pull request by portertech**

### CODE REVIEW

**Comment by portertech** [comment]
@coderanger Thoughts?

**Comment by coderanger** [comment]
:+1: Looks good!

**Comment by portertech** [comment]
`flag provided but not defined: -f` :( not backwards compatible.

**Comment by coderanger** [comment]
Looks like `build -f` was added in https://github.com/docker/docker/blob/master/CHANGELOG.md#150-2015-02-10.

**Comment by coderanger** [comment]
Current is 1.7.1, I would say 1.5.0 is not an unreasonable expectation.

**Comment by portertech** [comment]
I agree, I haven't had the need to upgrade. I will update the CHANGELOG.

**Pull request merged**
